package cmds

import (
	"fmt"
	"io"
)

func CmdHelp(ctx CmdContext, args []string, w io.Writer, errW io.Writer, stdin io.Reader) int {
	fmt.Fprintln(w, "Available commands:")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "FILESYSTEM")
	fmt.Fprintln(w, "  ls [-l|-a|-R|-S|-t|-F|-1|-h|-d] [path]  List directory contents")
	fmt.Fprintln(w, "  cat [-n|-A] <file>                      Display file contents")
	fmt.Fprintln(w, "  head [-n N|-c N] <file>                 Display first N lines (default 10)")
	fmt.Fprintln(w, "  tail [-n N|-c N|+N] <file>              Display last N lines (default 10)")
	fmt.Fprintln(w, "  tree [-L depth|-a|-d|-f] [path]          Show directory tree")
	fmt.Fprintln(w, "  stat <path>                              Show file info")
	fmt.Fprintln(w, "  wc [-l|-w|-c|-m] <file>                  Count lines, words, bytes")
	fmt.Fprintln(w, "  du [-a|-h|-s|-c] [path]                  Estimate file space usage")
	fmt.Fprintln(w, "  diff [-u|-q] <file1> <file2>             Compare two files")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "SEARCH")
	fmt.Fprintln(w, "  grep [-EFinrRohcvl] <pattern> [path]    Search for pattern in files")
	fmt.Fprintln(w, "    Basic regex by default; -E extended regex; -F fixed strings")
	fmt.Fprintln(w, "  find [path] [-name pat] [-type f|d]     Find files")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "TEXT PROCESSING")
	fmt.Fprintln(w, "  sort [-r|-n|-u|-f|-k N|-t SEP]          Sort lines")
	fmt.Fprintln(w, "  uniq [-c|-d|-i|-u]                       Filter duplicate lines")
	fmt.Fprintln(w, "  cut [-d DEL|-f FIELDS|-c CHARS|-s]       Cut sections from lines")
	fmt.Fprintln(w, "  sed [-n|-e EXPR] 's/pat/repl/flags'      Stream editor")
	fmt.Fprintln(w, "    Replacement escapes: \\n newline, \\t tab, \\\\ backslash")
	fmt.Fprintln(w, "    Escape delimiters with a backslash; backslash-newline inserts a newline")
	fmt.Fprintln(w, "  sed '/pat/a text' <file>                  Append text after matching lines")
	fmt.Fprintln(w, "  sed '/pat/a\\<text>' <file>              Append text, preserving leading whitespace")
	fmt.Fprintln(w, "  awk [-F SEP|-v VAR=VAL] 'program'        Pattern scanning")
	fmt.Fprintln(w, "  tr [-d|-s|-c] SET1 [SET2]                Translate characters")
	fmt.Fprintln(w, "  rev                                      Reverse each line")
	fmt.Fprintln(w, "  tac                                      Print lines in reverse")
	fmt.Fprintln(w, "  nl [-b a|t|-n ln|rn|rz|-w N|-s SEP]      Number lines")
	fmt.Fprintln(w, "  fold [-w N|-s]                            Wrap lines to width")
	fmt.Fprintln(w, "  paste [-d DEL|-s] <file> ...              Merge file lines")
	fmt.Fprintln(w, "  column [-t|-s SEP]                        Columnate lists")
	fmt.Fprintln(w, "  join [-1 F|-2 F|-t SEP] <f1> <f2>        Join sorted files")
	fmt.Fprintln(w, "  comm [-1|-2|-3] <file1> <file2>           Compare sorted files")
	fmt.Fprintln(w, "  expand [-t N]                             Convert tabs to spaces")
	fmt.Fprintln(w, "  unexpand [-t N|-a]                        Convert spaces to tabs")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "DATA")
	fmt.Fprintln(w, "  jq [-r|-c|-e|-s] <filter> [file]         JSON processor")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "UTILITIES")
	fmt.Fprintln(w, "  xargs [-I REPL|-d DEL|-n N|-0] <cmd>     Build commands from stdin")
	fmt.Fprintln(w, "  seq [-s SEP|-w] [FIRST] [INCR] LAST      Print number sequence")
	fmt.Fprintln(w, "  printf <format> [args]                    Format and print")
	fmt.Fprintln(w, "  date [-u] [+FORMAT]                       Display date/time")
	fmt.Fprintln(w, "  basename <path> [suffix]                  Strip directory")
	fmt.Fprintln(w, "  dirname <path>                            Strip last component")
	fmt.Fprintln(w, "  base64 [-d]                               Base64 encode/decode")
	fmt.Fprintln(w, "  md5sum/sha1sum/sha256sum [-c] [file]      Compute checksums")
	fmt.Fprintln(w, "  expr <expression>                         Evaluate expression")
	fmt.Fprintln(w, "  which <cmd>                               Locate command")
	fmt.Fprintln(w, "  type <cmd>                                Identify command type")
	fmt.Fprintln(w, "  time <cmd>                                Time a command")
	fmt.Fprintln(w, "  whoami / hostname                         Print user/host info")
	fmt.Fprintln(w, "  true / false                              Exit with 0 / 1")
	fmt.Fprintln(w, "")
	// WRITES and PUBLISHING are shown only when the session may use them
	// (Part B capability gating). A read-only session never sees this surface.
	if ctx.ActionAllowed(ActionWrite) {
		fmt.Fprintln(w, "WRITES")
		fmt.Fprintln(w, "  cmd > file  /  cmd >> file               Redirect output to a file")
		fmt.Fprintln(w, "  tee <file>                               Pass stdin to stdout and a file")
		fmt.Fprintln(w, "  patch <file>                             Apply a unified diff (atomic)")
		fmt.Fprintln(w, "  sed -i 's/a/b/' <file>                   Edit a file in place")
		fmt.Fprintln(w, "  sed -i '/pat/a\\<text>' <file>           Append after matching lines in place")
		fmt.Fprintln(w, "  mkdir [-p] <dir>                         Create directories")
		fmt.Fprintln(w, "  mv <source> <destination>                Move a file")
		fmt.Fprintln(w, "  rm [-r] [-f] <path>                      Remove files or directory trees")
		fmt.Fprintln(w, "  (writes are atomic; an overwrite fails if the file changed")
		fmt.Fprintln(w, "   since you last read it — cat it first, then write)")
		fmt.Fprintln(w, "")
	}
	if ctx.ActionAllowed(ActionPublish) {
		fmt.Fprintln(w, "PUBLISHING")
		fmt.Fprintln(w, "  publish <docset> <path>                  Publish content from stdin")
		fmt.Fprintln(w, "")
	}
	if ctx.ActionAllowed(ActionSpawn) {
		fmt.Fprintln(w, "ASYNC EXTERNAL WORK")
		fmt.Fprintln(w, "  spawn --writes <path> [--append] -- <cmd...>  Run a command async; write its output back")
		fmt.Fprintln(w, "  cat /jobs/<id>                           Check a spawned job's state")
		fmt.Fprintln(w, "  ls /jobs                                 List spawned jobs")
		fmt.Fprintln(w, "")
	}
	fmt.Fprintln(w, "NAVIGATION & SHELL")
	fmt.Fprintln(w, "  cd <path>                                Change directory")
	fmt.Fprintln(w, "  pwd                                      Print working directory")
	fmt.Fprintln(w, "  echo [-n|-e] <text>                      Print text")
	fmt.Fprintln(w, "  export [VAR=VAL]                         Set environment variable")
	fmt.Fprintln(w, "  unset <VAR>                              Remove variable")
	fmt.Fprintln(w, "  env / printenv [VAR]                     Print environment")
	fmt.Fprintln(w, "  set [-- args]                            Set/list variables")
	fmt.Fprintln(w, "  test / [ <expr> ]                        Conditional tests")
	fmt.Fprintln(w, "  read [-p PROMPT|-r] [VAR ...]            Read from stdin")
	fmt.Fprintln(w, "  source <file> / eval <cmd>               Execute commands")
	fmt.Fprintln(w, "  help                                     Show this help")
	fmt.Fprintln(w, "  exit / quit                              Close session")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "AGENT SKILLS")
	fmt.Fprintln(w, "  skills                                   Show Agent Skills usage and installed instructions")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Pipes are supported: grep pattern /dir | head -5 | sort -u")
	return 0
}
