package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/aakarim/go-openlore/pkg/rules"
	_ "github.com/aakarim/go-openlore/pkg/rules/link"
	_ "github.com/aakarim/go-openlore/pkg/rules/okfrule"
	_ "github.com/aakarim/go-openlore/pkg/rules/size"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: rulesdocs <output>")
		os.Exit(2)
	}
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by go generate; DO NOT EDIT. -->\n\n# Rules standard library\n\n")
	for _, member := range rules.DefaultRegistry().All() {
		manifest := member.Manifest()
		fmt.Fprintf(&output, "## `%s`\n\n```text\n", manifest.Path)
		rules.WriteDoc(&output, manifest)
		output.WriteString("```\n\n")
	}
	content := append(bytes.TrimSpace(output.Bytes()), '\n')
	if err := os.WriteFile(os.Args[1], content, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
